# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
name: Integration Tests

on:
  pull_request:
  push:
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
    tags: ["**"]
  workflow_dispatch:

jobs:
  container:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install testing requirements
        run: |
          pip install -r dev-requirements.txt
          # Install websocat, needed for integration tests
          wget -q https://github.com/vi/websocat/releases/download/v1.12.0/websocat.x86_64-unknown-linux-musl \
            -O /usr/local/bin/websocat
          chmod +x /usr/local/bin/websocat

      - name: Run Integration tests
        run: |
          export PYTHONUNBUFFERED=1
          py.test integration-tests/ -s

      # TODO: Check if the noVNC rendering works, perhaps by using playwright
      # https://playwright.dev/docs/test-snapshots
